
"use strict";$(document).ready(function(){$(document).on('click','.inner-choose:not(.active) .dc-btn',function(e){e.preventDefault();var th=$(this);th.closest('.inner-choose').addClass('active').siblings().removeClass('active');})
var fl=true;function onResize(){if(window.innerWidth<=767){if(fl){fl=false;void 0;window.addEventListener('scroll',onScrollC);}}else{if(!fl){fl=true;window.removeEventListener('scroll',onScrollC);$('.section-main').removeAttr('style');if($('body').hasClass('hidden-body')){$('body').removeClass('hidden-body');}
void 0;}}};var doit;doit=setTimeout(onResize,200);window.onresize=function(){clearTimeout(doit);doit=setTimeout(onResize,200);};var f=true;function onScrollC(){var scrTop=$(window).scrollTop();var headerHeight=$('.logo-wrap').outerHeight()+$('.topline-bg').outerHeight();var menu=$('.row-menu-mobile').outerHeight();if(scrTop>headerHeight&&f){f=false;void 0;$('.row-menu-mobile').addClass('row-menu-mobile_fixed');$('.section-main').css({marginTop:menu})}else if(scrTop<=headerHeight&&!f){f=true;$('.row-menu-mobile').removeClass('row-menu-mobile_fixed');$('.section-main').removeAttr('style');}}
var timer;$(document).on({mouseenter:function(){var th=$(this);timer=setTimeout(function(){var	imgContainer=th.closest('.slider-wrap').find('.main-slider__item-img'),imgHrefLg=th.attr('href'),imgPrev=imgContainer.find('img');th.addClass('-active').parent().siblings().find('.-active').removeClass('-active');$(imgContainer).animate({opacity:0,},200,function(){imgPrev.attr('src',imgHrefLg);imgContainer.animate({opacity:'1',},150);});},250);},mouseleave:function(){clearTimeout(timer);}},".slider-thumb__item-thumb:not(.-active)");if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){}
var linksArrow=$('.filter-list .has-children').children('a');$(linksArrow).on('click',function(e){e.preventDefault();$(this).toggleClass('active');$(this).next().slideToggle();})
$(document).on('click','.js-hamburger',function(e){e.preventDefault();$(this).toggleClass('is-active');if($('.row-menu-mobile').hasClass('row-menu-mobile_fixed')){var topMargin=$('.row-menu-mobile').outerHeight();$('.filter-wrap').css('top',topMargin);}else{var topMargin=$('.header').outerHeight();$('.filter-wrap').css('top',topMargin);}
void 0;if($('body').hasClass('hidden-body')){$('.topline-bg, .phone-wr, .icsbar__lnk-wrap').css('paddingRight','0');}else{$('.topline-bg, .phone-wr, .icsbar__lnk-wrap').css('paddingRight',getScrollBarWidth());}
$('body').toggleClass('hidden-body');$('.filter-wrap').toggleClass('filter-wrap_active');});$('input,textarea').focus(function(){$(this).data('placeholder',$(this).attr('placeholder')).attr('placeholder','');}).blur(function(){$(this).attr('placeholder',$(this).data('placeholder'));});$(document).on('click','.js-disabled',function(e){e.preventDefault();})
function validateEmail(email){var re=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email);}
function getScrollBarWidth(){var inner=document.createElement('p');inner.style.width="100%";inner.style.height="200px";var outer=document.createElement('div');outer.style.position="absolute";outer.style.top="0px";outer.style.left="0px";outer.style.visibility="hidden";outer.style.width="200px";outer.style.height="150px";outer.style.overflow="hidden";outer.appendChild(inner);document.body.appendChild(outer);var w1=inner.offsetWidth;outer.style.overflow='scroll';var w2=inner.offsetWidth;if(w1==w2)w2=outer.clientWidth;document.body.removeChild(outer);return(w1-w2);};});$(document).ready(function(){$('[data-fancybox]').fancybox({touch:false,smallBtn:false,});$('.fancy').fancybox({touch:false,smallBtn:true,toolbar:false,iframe:{css:{width:'482px'}},btnTpl:{smallBtn:'<div data-fancybox-close class="modal-close"></div>'}});$('input[type=tel]').mask("+7 (999) 999-99-99");$('.js-inner-choose1').matchHeight({byRow:false,property:'height',});$('.js-inner-choose2').matchHeight({byRow:false,property:'height',});$('.products-wrap .product-item__img-bg').matchHeight({byRow:true,property:'height',});$('.products-wrap .product-item__name').matchHeight({byRow:true,property:'height',});$('.products-wrap .product-item__price-wrap').matchHeight({byRow:true,property:'height',});$.fn.matchHeight._afterUpdate=function(event,groups){void 0;$(groups).each(function(i,item){var flag=true;$(item.elements).each(function(p,post){if($(post).hasClass('product-item__img-bg')){if(flag){flag=false;void 0;}}
if($(post).hasClass('inner-choose')){if(flag){flag=false;void 0;void 0;void 0;}}})});}
if($('.js-sticky-container').length){$('.js-filter-sticky').stickySidebar({containerSelector:'.js-sticky-container',topSpacing:20,bottomSpacing:20,minWidth:768});}
if($('.js-sidebar-container-sticky').length){$('.js-sidebar-sticky').stickySidebar({containerSelector:'.js-sidebar-container-sticky',topSpacing:20,bottomSpacing:20,minWidth:768});}});